server.port=${PORT_GATEWAY}

# oauth2 security
spring.security.oauth2.client.registration.gateway-client.client-id=${CLIENT_ID_GATEWAY}
spring.security.oauth2.client.registration.gateway-client.client-secret=${CLIENT_SECRET_GATEWAY}
spring.security.oauth2.client.registration.gateway-client.redirect-uri=${url.public.gateway}/login/oauth2/code/${CLIENT_ID_GATEWAY}
spring.security.oauth2.client.registration.gateway-client.scope=openid,profile,email
spring.security.oauth2.client.registration.gateway-client.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.gateway-client.provider=auth-server
spring.security.oauth2.client.provider.auth-server.issuer-uri=${url.public.auth-server}