# urls
url.public.gateway=${MAIN_HOST}:${PORT_GATEWAY}
url.public.auth-server=${MAIN_HOST}:${PORT_AUTH_SERVER}
url.front-end=${MAIN_HOST}:${PORT_FE}

# eureka
eureka.client.service-url.defaultZone=${INTERNAL_URL_DISCOVERY}/eureka/
eureka.instance.prefer-ip-address=true