services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PWD_MYSQL}
    ports:
      - "${DB_PORT_MYSQL}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  config-server:
    image: manhnk2/atpone-config-server:1.0
    container_name: config-server
    env_file:
      - .env
    environment:
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "${PORT_CONFIG_SERVER}:8888"
    networks:
      - nw-atpone
  discovery:
    image: manhnk2/atpone-discovery:1.0
    container_name: discovery
    env_file:
      - .env
    environment:
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "${PORT_DISCOVERY}:9999"
    depends_on:
      - config-server
    networks:
      - nw-atpone
  auth-server:
    image: manhnk2/atpone-auth-server:1.0
    container_name: auth-server
    env_file:
      - .env
    environment:
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "${PORT_AUTH_SERVER}:9000"
    depends_on:
      - config-server
      - discovery
    networks:
      - nw-atpone
  api-gateway:
    image: manhnk2/atpone-api-gateway:1.0
    container_name: api-gateway
    env_file:
      - .env
    environment:
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "${PORT_GATEWAY}:8080"
    depends_on:
      - config-server
      - discovery
      - auth-server
    networks:
      - nw-atpone
  system-setting-mgmt:
    image: manhnk2/atpone-system-setting-mgmt:1.0
    container_name: system-setting-mgmt
    env_file:
      - .env
    environment:
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "${PORT_SYS_SETTING_MGTMT}:8081"
    depends_on:
      - config-server
      - discovery
      - auth-server
    networks:
      - nw-atpone
networks:
  nw-atpone:
    driver: bridge
volumes:
  mysql_data: