services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file:
      - ../.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PWD_MYSQL}
    ports:
      - "${DB_PORT_MYSQL}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-uroot","-p${DB_PWD_MYSQL}"]
      interval: 10s
      timeout: 5s
      retries: 5
  config-server:
    image: ${DOCKER_USERNAME}/atpone-config-server:1.0
    container_name: config-server
    env_file:
      - ../.env
    environment:
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "${PORT_CONFIG_SERVER}:8888"
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:${PORT_CONFIG_SERVER}/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nw-atpone
  discovery:
    image: ${DOCKER_USERNAME}/atpone-discovery:1.0
    container_name: discovery
    restart: always
    env_file:
      - ../.env
    environment:
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "${PORT_DISCOVERY}:9999"
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - nw-atpone
  auth-server:
    image: ${DOCKER_USERNAME}/atpone-auth-server:1.0
    container_name: auth-server
    env_file:
      - ../.env
    environment:
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "${PORT_AUTH_SERVER}:9000"
    depends_on:
      discovery:
        condition: service_started
    networks:
      - nw-atpone
  api-gateway:
    image: ${DOCKER_USERNAME}/atpone-api-gateway:1.0
    container_name: api-gateway
    env_file:
      - ../.env
    environment:
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "${PORT_GATEWAY}:8080"
    depends_on:
      auth-server:
        condition: service_started
    networks:
      - nw-atpone
  system-setting-mgmt:
    image: ${DOCKER_USERNAME}/atpone-system-setting-mgmt:1.0
    container_name: system-setting-mgmt
    env_file:
      - ../.env
    environment:
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "${PORT_SYS_SETTING_MGTMT}:8081"
    depends_on:
      mysql:
        condition: service_healthy
      auth-server:
        condition: service_started
    networks:
      - nw-atpone
networks:
  nw-atpone:
    driver: bridge
volumes:
  mysql_data: