spring.application.name=config-server
server.port=${PORT_CONFIG_SERVER}

# remote configuration loading
spring.cloud.config.server.default-label=develop
spring.cloud.config.server.git.uri=${GIT_REPO}
spring.cloud.config.server.git.search-paths=be_config
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.username=${GIT_USERNAME}
spring.cloud.config.server.git.password=${GIT_TOKEN}