spring.application.name=config-server
server.port=${PORT_CONFIG_SERVER}

# remote configuration loading
spring.cloud.config.server.default-label=develop
spring.cloud.config.server.git.uri=https://github.com/IrisDuong/atpone.git
spring.cloud.config.server.git.search-paths=be_config
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.username=IrisDuong
spring.cloud.config.server.git.password=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