spring.application.name=discovery

# config server
spring.config.import=optional:configserver:${INTERNAL_URL_CONFIG_SERVER}

# eureka client
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=false

# retry
spring.cloud.config.retry.max-attempts=20
spring.cloud.config.retry.max-interval=10000
spring.cloud.config.retry.initial-interval=4000
spring.cloud.config.retry.multiplier=1.1
spring.cloud.config.fail-fast=true